#!/bin/sh

CATEGORIZE_FILE="./categorize.cfg"
CATEGORY="Graph"

./arbtt-stats --categorizefile=$CATEGORIZE_FILE \
              --for-each=day \
              --output-format=CSV \
              --category=$CATEGORY \
              --min-percentage=0.1 \
              > /tmp/daily.csv
./arbtt-stats --categorizefile=$CATEGORIZE_FILE \
              --for-each=minute \
              --output-format=CSV \
              --category=$CATEGORY \
              --min-percentage=0.1 \
              > /tmp/minute.csv

python3 readArbttStats.py -c 'misc' -d /tmp/daily.csv -m /tmp/minute.csv
